name: Create Release

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0, v1.2.1, etc.
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for creating releases
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3
    
    - name: Build all versions
      run: ./build-all.sh
    
    - name: Prepare release artifacts
      run: |
        mkdir release-artifacts
        find builds -name "*.jar" -exec cp {} release-artifacts/ \;
        ls -la release-artifacts/
    
    - name: Get version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get_version.outputs.VERSION }}
        release_name: DelayBeGone ${{ steps.get_version.outputs.VERSION }}
        body: |
          ## DelayBeGone ${{ steps.get_version.outputs.VERSION }}
          
          Removes the 5-tick shield blocking delay in Minecraft.
          
          ### Supported Versions
          - Minecraft 1.20.4 (NeoForge 20.4.249)
          - Minecraft 1.20.6 (NeoForge 20.6.138)
          - Minecraft 1.21.1 (NeoForge 21.1.200)
          - Minecraft 1.21.3 (NeoForge 21.3.89)
          - Minecraft 1.21.4 (NeoForge 21.4.150)
          - Minecraft 1.21.5 (NeoForge 21.5.91)
          - Minecraft 1.21.6 (NeoForge 21.6.20-beta)
          - Minecraft 1.21.7 (NeoForge 21.7.25-beta)
          - Minecraft 1.21.8 (NeoForge 21.8.31)
          
          ### Installation
          1. Install NeoForge for your Minecraft version
          2. Download the JAR file for your Minecraft version
          3. Place it in your `mods` folder
          4. **Important**: This mod must be installed on the server to function properly
          
          ### Changes
          - Add release notes here
        draft: false
        prerelease: false
    
    - name: Upload Release Assets
      run: |
        for file in release-artifacts/*.jar; do
          filename=$(basename "$file")
          echo "Uploading $filename"
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -H "Content-Type: application/java-archive" \
               --data-binary @"$file" \
               "https://uploads.github.com/repos/${{ github.repository }}/releases/${{ steps.create_release.outputs.id }}/assets?name=$filename"
        done